### ISSUE TITLE
Possible typo in demo

### ISSUE THREAD

**Issue by lc82111** [kylechampley/XrayPhysics#3]
`#########################################################################################
# Example 4: Effective Energy Through a Material of Variable Thickness
#########################################################################################
thicknesses = np.array(range(26))/10.0
e_effs = thicknesses.copy()
for n in range(thicknesses.size):
    e_effs[n] = physics.effectiveEnergy('H2O', 1.0, thicknesses[n], s_total, Es)
if whichPlot == 4:
    plt.plot(thicknesses, e_effs, 'k-')
    plt.title('Effective Energy (keV)')
    plt.xlabel('thickness (cm)')
    plt.ylabel('LAC (cm^-1)')
    plt.show()`

The label 'LAC (cm^-1)' on the y-axis in this context appears to be a mistake. Given the code, the y-axis should represent the effective energy in keV, not the Linear Attenuation Coefficient (LAC). The physics.effectiveEnergy function is calculating the effective energy of the X-ray beam after passing through a material of a certain thickness, not the LAC.

**Comment by kylechampley** [comment]
Yep, that is a typo.  Really appreciate you bringing this to my attention!  I fixed it and pushed the changes.
